// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240209115052_AddParameterTypeCode")]
    partial class AddParameterTypeCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid[]>("Images")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Models.AssetCategoryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryParameterId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryParameterId");

                    b.ToTable("AssetCategoryParameters");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseForApi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4695b6e-8f3f-4aec-b67d-ff4e70b7efc0"),
                            Name = "Жилой комплекс",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("f1ce8c18-7202-4060-a52f-87b03f8681be"),
                            Name = "Дом",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("30dd86f1-4684-4fa2-88d1-fb48f8b0bbaa"),
                            Name = "Квартира",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("a22ea67a-e82b-4708-b473-b55e7e893a7b"),
                            Name = "Подъезд",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("67c40cb8-a870-4a14-b438-8e929b944f4b"),
                            Name = "Этаж",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("ff75070d-68ed-4ed3-8adc-0abb904a7c73"),
                            Name = "Игровая площадка",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("c813864e-f33f-4a45-a3bf-89af74e5bafd"),
                            Name = "Детсткая площадка",
                            UseForApi = true
                        });
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParameterId");

                    b.ToTable("CategoryParameters");
                });

            modelBuilder.Entity("Models.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Models.AssetCategoryParameter", b =>
                {
                    b.HasOne("Models.Asset", "Asset")
                        .WithMany("Categories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.CategoryParameter", "CategoryParameter")
                        .WithMany("AssetCategoryParameters")
                        .HasForeignKey("CategoryParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CategoryParameter");
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany("CategoryParameters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Parameter", "Parameter")
                        .WithMany("CategoryParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Models.Asset", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Navigation("CategoryParameters");
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.Navigation("AssetCategoryParameters");
                });

            modelBuilder.Entity("Models.Parameter", b =>
                {
                    b.Navigation("CategoryParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
