// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240216195909_FixRequired")]
    partial class FixRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid[]>("Images")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Models.AssetCategoryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryParameterId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryParameterId");

                    b.ToTable("AssetCategoryParameters");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseForApi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("501786d1-49db-4efd-a371-da1cc3bd7d97"),
                            Name = "Жилой комплекс",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("1f6b25b5-0f51-4e47-b8f3-dc2a027e235e"),
                            Name = "Дом",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("2193f21d-5a4b-49a1-aaf1-19ae49ba914a"),
                            Name = "Квартира",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("6b4cd52a-9501-4fa1-a6d1-6bbaf338965d"),
                            Name = "Подъезд",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("90ac0a5b-b256-4e3f-8105-1f163a939dab"),
                            Name = "Этаж",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("fc52621b-1485-4eb8-9997-c3e05490bba7"),
                            Name = "Игровая площадка",
                            UseForApi = true
                        },
                        new
                        {
                            Id = new Guid("45eddaba-231b-4402-9b67-8bb6129dda9e"),
                            Name = "Детсткая площадка",
                            UseForApi = true
                        });
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParameterId");

                    b.ToTable("CategoryParameters");
                });

            modelBuilder.Entity("Models.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Models.AssetCategoryParameter", b =>
                {
                    b.HasOne("Models.Asset", "Asset")
                        .WithMany("Categories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.CategoryParameter", "CategoryParameter")
                        .WithMany("AssetCategoryParameters")
                        .HasForeignKey("CategoryParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CategoryParameter");
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany("CategoryParameters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Parameter", "Parameter")
                        .WithMany("CategoryParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Models.Asset", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Navigation("CategoryParameters");
                });

            modelBuilder.Entity("Models.CategoryParameter", b =>
                {
                    b.Navigation("AssetCategoryParameters");
                });

            modelBuilder.Entity("Models.Parameter", b =>
                {
                    b.Navigation("CategoryParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
